#
# FILE: .mise.toml
#
# DESCRIPTION:
# This is the central configuration file for the Mise tool manager. It defines the project's
# toolset and declaratively manages environment variables, including secrets.
#
# Version: 2025-09-11 22:45:00 AEST

# --- Env Configuration ---
#
# WHY: This section is the core of the declarative environment setup. Mise automatically
# activates this environment when you `cd` into the project directory.
# The `_.file` directive tells Mise to load variables from these files, in order.
# Critically, Mise has built-in SOPS support; it will recognize `.env.sops.yaml`
# and automatically decrypt it in memory before loading the variables. This replaces
# the need for any custom profile scripts.
#
[env]
_.file = [ ".config/env", ".config/.env.sops.yaml" ]
_.path = [ ]
# _.python.venv = { path = ".venv", create = false, uv_create_args = ['--seed'] }

# --- Mise Configuration ---
[settings]
experimental = true
# sops.disable_git_check = true # Use if your .git directory is outside the project root

# --- Tools ---
#
# WHY: Defining tool versions here ensures every developer uses the exact same dependencies,
# eliminating "it works on my machine" problems. `mise install` will automatically

# provision these versions. Using "latest" is suitable for this template, but for
# production projects, pinning to specific versions (e.g., python = "3.13.0") is recommended.
#
[tools]
age = "latest"
hadolint = "latest"
jq = "latest"
node = "latest"
python = "3.13"
shellcheck = "latest"
sops = "latest"
uv = "latest"
yq = "latest"
