# Version: 2025-09-11 22:23:00 AEST
#
# DESCRIPTION:
# This Docker Compose file defines the services for the development container.
# It centralizes environment configuration by using `env_file` to load
# variables from `.devcontainer/devcontainer.env`, ensuring a single source of truth.
#
name: devspace
services:
  trixie:
    build:
      context: .
      dockerfile: Dockerfile
      # Build-time arguments are passed from the environment file.
      args:
        USERNAME: ${USERNAME:-vscode}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    command: sleep infinity
    #
    # WHY: env_file provides a single, authoritative source for environment variables,
    # making configuration cleaner and less error-prone than a mixed environment: block.
    # All container-wide environment variables should be defined in `devcontainer.env`.
    #
    env_file: devcontainer.env
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename:-workspace}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      #
      # OPTIONAL: To use GPG keys from your host machine for things like Git commit signing,
      # uncomment the following volume mount and set LOCAL_GNUPG_DIR in `.devcontainer/devcontainer.env`.
      # e.g., LOCAL_GNUPG_DIR=${HOME}/.gnupg
      #
      # - ${LOCAL_GNUPG_DIR}:/home/${USERNAME}/.gnupg:ro
