# Version: 2025-09-11 22:23:00 AEST
#
# DESCRIPTION:
# This Docker Compose file defines the services for the development container.
# It centralizes environment configuration by using `env_file` to load
# variables from `.devcontainer/devcontainer.env`, ensuring a single source of truth.
#
name: devspace
services:
  trixie:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #
        # WHY: These variables are read from `devcontainer.env` and passed into the
        # Dockerfile build process. This is the core mechanism for dynamic user mapping.
        #
        USERNAME: ${USERNAME:-vscode}
        GROUPNAME: ${GROUPNAME:-vscode}
        USER_UID: ${UID:-1000}
        USER_GID: ${GID:-1000}
    command: sleep infinity
    #
    # WHY: The `env_file` is the single source of truth for variables needed by
    # Docker Compose at runtime or during the build.
    #
    env_file: devcontainer.env
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename:-devspace}:cached
      - /var/run/docker.sock:/var/run/docker.sock
      #
      # OPTIONAL: To use GPG keys from your host machine for things like Git commit signing,
      # uncomment the following volume mount and set LOCAL_GNUPG_DIR in `.devcontainer/devcontainer.env`.
      # e.g., LOCAL_GNUPG_DIR=${HOME}/.gnupg
      #
      # - ${LOCAL_GNUPG_DIR}:/home/${USERNAME}/.gnupg:ro
