# Version: 2025-09-21 14:42:18 AEST
#
# DESCRIPTION:
# This Docker Compose file defines the development environment service. It is
# designed to be context-aware, reading user and project details from the
# `.env` file to build and configure the container dynamically.
#
name: devspace  # COMPOSE_PROJECT_NAME
services:
  trixie:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # These variables are automatically read from `.env` and passed into the
        # Dockerfile build process.
        DOCKER_USER: ${DOCKER_USER:-vscode}
        DOCKER_GROUP: ${DOCKER_GROUP:-vscode}
        PUID: ${PUID:-1000}
        PGID: ${PGID:-1000}

    container_name: '${COMPOSE_PROJECT_NAME}'
    env_file: .env

    # The `user` directive sets the default runtime user for the container.
    # This works in concert with the user creation logic in the Dockerfile and
    # the `remoteUser` setting in `devcontainer.json` to ensure a seamless
    # and permission-error-free experience.
    user: ${PUID:-1000}:${PGID:-1000}

    volumes:
      # Mount the entire project directory into the container.
      - ..:/workspaces/${localWorkspaceFolderBasename:-devspace}:cached

      # Mount the Docker socket to enable Docker-out-of-Docker.
      - /var/run/docker.sock:/var/run/docker.sock

  # --- Optional Services ---
  # The following services are commented out but can be enabled for projects
  # requiring a database or cache.

  # postgres:
  #   image: postgres:16
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres

  # redis:
  #   image: redis:7
  #   restart: unless-stopped

volumes:
  postgres-data:
