#
# GITHUB WORKFLOW: ci.yml
#
# DESCRIPTION:
# This CI pipeline now calls the centralized `mise` lint task, ensuring it runs
# the exact same checks as the local pre-commit hooks.
#
# Version: 2025-09-12 16:45:00 AEST -> Updated 2025-09-15 16:30:00 AEST
#
name: "Continuous Integration"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: "Validate Project Integrity"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Install Mise"
        run: |
          curl -fsSL https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "Install Project Tools"
        run: mise install

      - name: "Run Linters via Mise"
        #
        # WHY: This is now the single source of truth for linting. It executes the
        # `lint` task defined in `.config/mise/tasks.toml`, which runs all sub-tasks
        # for shellcheck, shfmt, and hadolint.
        #
        run: mise run lint

      - name: "Optional: Run Link Checker (DRY Gate)"
        if: always()
        run: mise run link-check
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Build Devcontainer Image"
        run: |
          echo "--- Building Devcontainer Image ---"
          cp .devcontainer/devcontainer.env.example .devcontainer/devcontainer.env
          docker compose -f .devcontainer/docker-compose.yml build
